# Generated by Django 5.2.11 on 2026-03-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BinaryField(default=True)),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LLms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField(unique=True)),
                ('input_token_cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('output_token_cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('context_length', models.IntegerField()),
                ('max_output_tokens', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm', to='providers.providers')),
            ],
            options={
                'unique_together': {('name', 'provider')},
            },
        ),
    ]
