# Generated by Django 5.2.11 on 2026-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llms',
            name='input_token_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='llms',
            name='output_token_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
