# Generated by Django 5.2.11 on 2026-03-10 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user_alter_message_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'),
        ),
    ]
