# Generated by Django 5.2.11 on 2026-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
